### ISSUE TITLE
OpenTelemetry agent with version 1.4.x report metrics without values

### ISSUE THREAD

**Issue by SodaDev** [aws-observability/aws-otel-java-instrumentation#71] opened 2021-08-05 16:27 UTC
After switching to the new opentelemetry agent in version: v 1.4.1 from 1.2.0 metrics exported to the new relic are always 0. I can see labels that are added there on my custom metrics and I can see agent reported metrics that are sent. Yet they have always value equal to 0.

Params that I use:
-javaagent:/...somePaths.../aws-opentelemetry-agent.jar -Dotel.javaagent.debug=true -Dotel.metrics.exporter=otlp -Dotel.instrumentation.runtime-metrics.enabled=true 

And ENV Variables that I use:
OTEL_RESOURCE_ATTRIBUTES=service.name=someappName,service.namespace=somenamespace,service.instance.id=mymachine.local
OTEL_EXPORTER_OTLP_ENDPOINT=http://collectorIp:4317
OTEL_PROPAGATORS=xray

After replacing path to jar with agent in version 1.2.0 everything works just fine

**Comment by anuraaga** [comment] 2021-08-10 04:11
Hi @SodaDev - with metrics having been still not stable in OpenTelemetry, there have been significant changes to the data model, in particular some values are reported in OTLP in a different field. Can you try setting `-Dotel.metrics.exporter=logging` and see if the actual metrics exported have values, just in a different format than you were using before?

**Comment by SodaDev** [comment] 2021-08-10 06:59
@anuraaga When I have used that option it is reported in the same way. Do you think it's related to the NewRelic exporter not being updated?

**Comment by anuraaga** [comment] 2021-08-10 08:28
@SodaDev Does the output of the logging exporter contain the data you expect, not 0? If so then yes the issue seems like it is on the collector side probably not supporting the new proto. @mxiamxia do you know the OTLP protocol status of the collector?

**Comment by SodaDev** [comment] 2021-08-10 11:03
I have used collector setup like this:

receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  memory_limiter:
    check_interval: 15s
    limit_mib: 256
  batch:
exporters:
  logging:
    loglevel: debug
  awsxray:
  newrelic:
    apikey: 
    timeout: 30s
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ awsxray, newrelic, logging ]
    metrics:
      receivers: [ otlp ]
      exporters: [ newrelic, logging ]I can see logs like:


I can see logs like one below:

{2021-08-10 10:59:58.861862073 +0000 UTC m=+44.910712695, Level:debug, Caller:github.com/open-telemetry/opentelemetry-collector-contrib/exporter/newrelicexporter@v0.29.1-0.20210630203112-81d57601b1bc/transformer.go:357, Message:Converting metric to gauge where AggregationTemporality != Delta, Stack:}

I will try to compare trace log from 1.2 vs 1.4 now

**Comment by SodaDev** [comment] 2021-08-10 11:14
I can see that this log is the same in 1.2 and 1.4

**Comment by SodaDev** [comment] 2021-08-10 11:19
This is how it looks like in NewRelic
[
![Screenshot 2021-08-10 at 13 16 54](https://user-images.githubusercontent.com/3107410/128857983-ba4dff6d-9821-4c29-b2b3-4bb83468558c.png)
](url)

**Comment by SodaDev** [comment] 2021-08-12 07:59
@anuraaga is there anything that I can provide to make investigation easier for you guys?

**Comment by anuraaga** [comment] 2021-08-12 09:03
@SodaDev With the logging exporter enabled like you have you should be seeing a dump of actual metric values. Can you post some examples of those?

This does feel like an issue that may be better in the opentelemetry-collector-contrib repo, because we can also ask new relic folks to take a look. I would also try using the latest version of the opentelemetry-collector-contrib binary rather than the collector that is part of ADOT (aws-otel-collector). It is newer and otherwise has no real downside.

**Comment by SodaDev** [comment] 2021-08-12 09:58
@anuraaga With this setup I can't see any data related to the metrics, only the log I've pasted. I watched for logs under /var/log/amazon/aws-otel-collector/aws-otel-collector.log

**Comment by anuraaga** [comment] 2021-08-13 03:13
@SodaDev Sorry I realized that you probably don't see the logs because `loglevel: debug` for the `logging` exporter - can you change it to `loglevel: info` and see if it starts printing metrics?

**Comment by SodaDev** [comment] 2021-08-16 07:25
@anuraaga I might be wrong, but loglevel debug is also printing logs on the info level. I have used file exporter for checking logs as there was still almost nothing in `/var/log/amazon/aws-otel-collector/aws-otel-collector.log`.

I found some difference between 1.2 and 1.4. The new version does not send value. I have attached logged values:

[Trace14And12.zip](https://github.com/aws-observability/aws-otel-java-instrumentation/files/6990450/Trace14And12.zip)


Here is example diff on part of the log:
![Screenshot 2021-08-16 at 09 25 06](https://user-images.githubusercontent.com/3107410/129526455-4a2c2b97-33b7-4bb2-92f7-527884f861ad.png)

**Comment by anuraaga** [comment] 2021-08-16 08:15
Thanks @SodaDev for this dump it is very helpful. There does seem to be a problem with the 1.4 agent. Metrics changed significantly in 1.4, and are changing again significantly in 1.5 (I'm writing the conversion PR right now...). Given the huge amount of drift, I don't think we'll be able to fix the issue per se, but we will make sure to verify the behavior of the runtime.jvm metrics after applying these big changes to fix by 1.5.

**Comment by SodaDev** [comment] 2021-08-16 08:22
@anuraaga Thanks a lot for that info! :) Do you know where 1.5 will be released?

**Comment by anuraaga** [comment] 2021-08-16 08:25
@SodaDev We aim to release a new version monthly, though can't provide exact dates for a release. Hope to get it out as soon as possible though.

**Comment by anuraaga** [comment] 2021-08-17 06:56
@SodaDev After a bit more digging, we realized that the issue is probably an incompatibility with the java instrumentation's metrics and the collector's receiver. So technically, it should be the next release of `aws-otel-collector` which fixes your problem, not this instrumentation.

**Comment by driverpt** [comment] 2021-09-01 08:15
@anuraaga , was this fixed with v1.5.0?

**Comment by anuraaga** [comment] 2021-09-01 08:18
Hi @driverpt and @SodaDev - 1.5.0 was released! My understanding is the latest version of this agent and the collector should be speaking a compatible protocol so this should be fixed. Can you try it out?

**Comment by driverpt** [comment] 2021-09-01 08:18
I'm only asking because i did not see anything regarding this issue in the Changelog

**Comment by anuraaga** [comment] 2021-09-01 08:24
@driverpt After some investigation the issue seemed to be due to the collector version, not the agent actually

https://github.com/aws-observability/aws-otel-java-instrumentation/issues/71#issuecomment-900043576

Nothing changed in the metric export format between 1.4.x and 1.5.x in this agent actually so nothing in the changelogs.

**Comment by SodaDev** [comment] 2021-09-01 08:55
@anuraaga I can see that with collector in v0.12.0 it works again :)

**Comment by anuraaga** [comment] 2021-09-01 08:58
Thanks for confirming @SodaDev! Will close out this issue then.

**Closed by anuraaga** 2021-09-01 08:58 UTC
